import { AlignText } from '../../../src/constants.js';

export const props = [

  {
    name: 'Movies',
    radius: 0.88,
    itemLabelRadius: 0.92,
    itemLabelRadiusMax: 0.4,
    itemLabelRotation: 0,
    itemLabelAlign: AlignText.right,
    itemLabelBaselineOffset: -0.5,
    itemLabelFont: 'sans-serif',
    itemBackgroundColors: ['#c7160c', '#fff'],
    itemLabelColors: ['#fff', '#000'],
    rotationSpeedMax: 700,
    rotationResistance: -70,
    itemLabelFontSize: 100,
    lineWidth: 0,
    overlayImage: './img/example-2-overlay.svg',
    items: [
      { label: 'deadlift abhiraj' },
      { label: 'Body building with hriday,arfath,shubham and anshuman' },
      { label: 'Sell condom to 2nd year' },
      { label: 'Ask muthukumar to recreate this reel' },
      { label: 'Propose Ayush Kumar Singh romantically' },
      { label: 'Dance with pranav romantically and post on insta' },
      { label: 'Pranav dances and Parth plays the mridangam' },
      { label: 'Just a minute on some shit topics' },
      { label: 'Balance balloon on nose tip and dance' },
      { label: 'Shot with a junior' },
      { label: 'Dance with Calvin' },
      { label: 'a minute on why web club (or your SIG) is the worst' },
      { label: 'prank call your favourite club super senior' },
      { label: 'Teach Parth how to dance' },
      { label: 'pretend tennis and make moaning sounds while making shot' },
      { label: 'rapid fire' },
      { label: 'show us your hidden talent' },
      { label: 'reveal the most cringe incident you had in college' },
      { label: 'speech on why boozing is important' },
      { label: 'hot pose for wec calendar shoot' },
      { label: 'seduce hriday' },
      { label: 'ask durga to teach swimming' },
      { label: 'shashank paint wec logo with his nose, water colour' },
      { label: 'Propose someone in the crowd' },
      { label: 'Ramp walk in a weird way' },
      { label: 'Vikas and sathwik salsa dance' },
      { label: 'hug all same gender second year\'s' },
      { label: 'do (6 x 9) + 6 + 9 pushups' },
      { label: 'roast iris tech lead' },
      { label: 'couple dance with samhita' },
      { label: 'selfie with your sig chair and post it on linkedin' },
      { label: 'send 1000 rs to the host' },
      { label: 'call rakshita and scold her for not coming' },
      { label: 'parth call danish,tell why he was the worst admin lead' },
      { label: 'parth to dance on dil vich' },
      { label: 'macchli game with ur 2 friends, loser propose chinmaya' },
    ],
  },

];